<Project Sdk="Aspire.AppHost.Sdk/13.3.3">

  <ItemGroup>
    <ProjectReference Include="..\TaskManager.Api\TaskManager.Api.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>d3ac30db-92aa-4e71-a99f-fdd0e08bd24b</UserSecretsId>
  </PropertyGroup>

</Project>
